#!/bin/bash
for data in $(ls -l |grep ^d |cut -d ' ' -f 13)
	do
		cd "$data"
		pwd
		/home/dongxinran/miniconda3/bin/sjaracne local -e input.exp -g tf.txt -n 100 -o  output_tf_sjaracne_ASD_vs_TD_out_.final
		/home/dongxinran/miniconda3/bin/sjaracne local -e input.exp -g sig.txt -n 100 -o  output_sig_sjaracne_ASD_vs_TD_out_.final
		echo "-------done-------"
		cd ../
	done
