gse27919067_all_gene <- draw.volcanoPlot(dat=gse_list[["GSE27919067"]]$DE$ASD.Vs.TD,label_col='ID',
                          logFC_col='logFC',
                          Pv_col='adj.P.Val',
                          logFC_thre=0.2,
                          Pv_thre=0.4,
                          main='Volcano Plot for ASD.Vs.TD of GSE27919067',
                          show_label=F,
                          label_type = 'origin',
                          label_cex = 0.5,
                          show_plot = F);nrow(gse27919067_all_gene)/nrow(gse_list[["GSE27919067"]]$DE$ASD.Vs.TD);
gse28521_all_gene <- draw.volcanoPlot(dat=gse_list[["GSE28521"]]$DE$ASD.Vs.TD,label_col='ID',
                          logFC_col='logFC',
                          Pv_col='P.Value',
                          logFC_thre=0.25,
                          Pv_thre=0.05,
                          main='Volcano Plot for ASD.Vs.TD of GSE28521',
                          show_label=F,
                          label_type = 'origin',
                          label_cex = 0.5,
                          show_plot = F);nrow(gse28521_all_gene)/nrow(gse_list[["GSE28521"]]$DE$ASD.Vs.TD)
gse64018_all_gene <- draw.volcanoPlot(dat=gse_list[["GSE64018"]]$DE$ASD.Vs.TD,label_col='ID',
                          logFC_col='logFC',
                          Pv_col='adj.P.Val',
                          logFC_thre=0.45,
                          Pv_thre=1e-1,
                          main='Volcano Plot for ASD.Vs.TD of GSE64018',
                          show_label=F,
                          label_type = 'origin',
                          label_cex = 0.5,
                          show_plot = F);nrow(gse64018_all_gene)/nrow(gse_list[["GSE64018"]]$DE$ASD.Vs.TD)
