# gse113834_all_driver <- draw.volcanoPlot(dat=gse_list[["GSE113834"]]$final_ms_tab,label_col='originalID_label',
#                           logFC_col='logFC.ASD.Vs.TD_DA',
#                           Pv_col='P.Value.ASD.Vs.TD_DA',
#                           logFC_thre=0.05,
#                           Pv_thre=1e-6,
#                           main='Volcano Plot for ASD.Vs.TD of GSE113834',
#                           show_label=F,
#                           label_type = 'origin',
#                           label_cex = 0.5,
#                           show_plot = T);nrow(gse113834_all_driver)/nrow(gse_list[["GSE113834"]]$final_ms_tab);
gse27919067_all_driver <- draw.volcanoPlot(dat=gse_list[["GSE27919067"]]$final_ms_tab,label_col='originalID_label',
                               logFC_col='logFC.ASD.Vs.TD_DA',
                               Pv_col='P.Value.ASD.Vs.TD_DA',
                               logFC_thre=0.04,
                               Pv_thre=0.02,
                               main='Volcano Plot for ASD.Vs.TD of GSE27919067',
                               show_label=F,
                               label_type = 'origin',
                               label_cex = 0.5,
                               show_plot = F);nrow(gse27919067_all_driver)/nrow(gse_list[["GSE27919067"]]$final_ms_tab);
gse28521_all_driver <- draw.volcanoPlot(dat=gse_list[["GSE28521"]]$final_ms_tab,label_col='originalID_label',
                          logFC_col='logFC.ASD.Vs.TD_DA',
                          Pv_col='P.Value.ASD.Vs.TD_DA',
                          logFC_thre=0.1,
                          Pv_thre=0.04,
                          main='Volcano Plot for ASD.Vs.TD of GSE28521',
                          show_label=F,
                          label_type = 'origin',
                          label_cex = 0.5,
                          show_plot = F);nrow(gse28521_all_driver)/nrow(gse_list[["GSE28521"]]$final_ms_tab)
gse64018_all_driver <- draw.volcanoPlot(dat=gse_list[["GSE64018"]]$final_ms_tab,label_col='originalID_label',
                          logFC_col='logFC.ASD.Vs.TD_DA',
                          Pv_col='P.Value.ASD.Vs.TD_DA',
                          logFC_thre=0.055,
                          Pv_thre=1e-2,
                          main='Volcano Plot for ASD.Vs.TD of GSE64018',
                          show_label=F,
                          label_type = 'origin',
                          label_cex = 0.5,
                          show_plot = F);nrow(gse64018_all_driver)/nrow(gse_list[["GSE64018"]]$final_ms_tab)
